version: '3.3'
services:
    mongo:
        build: 
            context: .
            dockerfile: mongo.Dockerfile
        ports:
            - '27017:27017'
        container_name: ipostu-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        volumes:
            - ./_container_data:/data/db
